services:
  oabot:
    build:
      context: .
      dockerfile: Dockerfile
    image: oabot:latest
    container_name: oabot
    environment:
      TZ: "${SYSTEM_TZ:-UTC}"
      BOT_TOKEN: "${BOT_TOKEN:?BOT_TOKEN is not set}"
      COMMAND_PREFIX: "${COMMAND_PREFIX:->}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
